INSERT INTO `movie` (`category_id`, `title`, `description`, `year`, `img`, `likes`) VALUES
(1, 'The Road Trip', 'Lorem Ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p1.PNG?raw=true', 0),
(1, 'Wynnonna Fear', 'Lorem ipsum', 2017, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p2.PNG?raw=true', 0),
(1, 'Club de Sherifs', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p3.PNG?raw=true', 0),
(1, 'Grey\'s Anatomy', 'lorem ipsum', 2008, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p4.PNG?raw=true', 0),
(2, 'Step Up 2 ', 'lorem ipsum', 2009, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p5.PNG?raw=true', 0),
(2, 'Liquid Science', 'lorem ipsum', 2019, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p6.PNG?raw=true', 0),
(1, '13 Reasons Why', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p7.PNG?raw=true', 0),
(2, 'The Staircase', 'lorem ipsum', 2019, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p8.PNG?raw=true', 0),
(2, 'The Vietnam War', 'lorem ipsum', 2017, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p9.PNG?raw=true', 0),
(2, 'The Covnan', 'lorem ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p10.PNG?raw=true', 0),
(1, 'Marcella', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p11.PNG?raw=true', 0),
(1, 'Riverdale', 'lorem ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/p12.PNG?raw=true', 0),
(2, 'Luxe Cage', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t1.PNG?raw=true', 0),
(1, 'The Ranch', 'lorem ipsum', 2017, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t2.PNG?raw=true', 0),
(3, 'Kissing Booth', 'lorem ipsum', 2019, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t5.PNG?raw=true', 0),
(1, 'Night Shift', 'lorem ipsum', 2020, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t6.PNG?raw=true', 0),
(1, 'Hawaii Five-O', 'lorem ipsum', 1999, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv1.PNG?raw=true', 0),
(3, 'Flash', 'lorem ipsum', 2019, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv3.PNG?raw=true', 0),
(1, 'Black Lighting', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv4.PNG?raw=true', 0),
(3, 'New Girl', 'lorem ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv5.PNG?raw=true', 0),
(2, 'The Legends', 'lorem ipsum', 2015, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv6.PNG?raw=true', 0),
(3, 'Agent Of Shield', 'lorem ipsum', 2014, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv7.PNG?raw=true', 0),
(2, 'Marlon', 'lorem ipsum', 2015, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv8.PNG?raw=true', 0),
(3, 'Cooking', 'lorem ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv9.PNG?raw=true', 0),
(3, 'Queer Eye', 'lorem ipsum', 2020, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv10.PNG?raw=true', 0),
(2, 'Shooter', 'lorem ipsum', 2017, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv11.PNG?raw=true', 0),
(1, 'Jessica Jones', 'lorem ipsum', 2017, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv12.PNG?raw=true', 0),
(2, 'Wanted', 'lorem ipsum', 2015, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m1.PNG?raw=true', 0),
(2, 'The Bourne Ultimatum', 'lorem ipsum', 2013, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m2.PNG?raw=true', 0),
(2, 'Guardians Of The Galaxy', 'lorem ipsum', 2013, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m3.PNG?raw=true', 9),
(2, 'National Treasure', 'lorem ipsum', 2015, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m4.PNG?raw=true', 0),
(2, 'Bad Boys', 'lorem ipsum', 2010, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m5.PNG?raw=true', 0),
(3, 'Bright', 'lorem ipsum', 2016, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/m6.PNG?raw=true', 0),
(3, 'Brain On Fire', 'lorem ipsum', 2018, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/o4.PNG?raw=true', 0),
(1, 'Arrested Development', 'lorem ipsum', 2019, 'https://github.com/carlosavilae/Netflix-Clone/blob/master/img/o6.PNG?raw=true', 0),
(3, 'Stranger Things', 'lorem ipsum', 2017, 'https://cdn.static01.nicematin.com/media/npo/mobile_1440w/2020/04/raw.jpg', 0),
(3, 'Killing Eve', 'lorem ipsum', 2018, 'https://lh3.googleusercontent.com/proxy/N5Mi4L8Z9q03wQN4dpHqYKM1_UUPG5tEyiIPS1XCNYN7ETxuq06dmj0hqCzJduaB_kHuAuewfaqDdfbfTJ-9w6-OmEcZzWkbHyfM7BnaSwYES3cT9tPbKqQmHylONnmG3RF27PP-ikjh5YOFBD_33K0v_pICQ-J0ysY5kjqwPA', 0),
(3, 'Rick & Morty', 'lorem ipsum', 2017, 'https://assets.change.org/photos/6/or/bi/UeorbIYnzrPxsSP-800x450-noPad.jpg?1538805188', 0);
